services:
  mycoursereviews:
    image: mycoursereviews:latest
    container_name: mycoursereviews
    env_file:
      - .env.local
    environment:
      - PUID=1000
      - PGID=1000
      - PORT=3200
    ports:
      - 3200:3200
    networks:
      - csclub
    extra_hosts:
      - "auth.csclub.org.au:host-gateway"

networks:
  csclub:
    external: true
